export const FETCH_REPOS_REQUEST = "FETCH_REPOS_REQUEST";
export const FETCH_REPOS_SUCCESS = "FETCH_REPOS_SUCCESS";
export const FETCH_REPOS_FAILURE = "FETCH_REPOS_FAILURE";
export const SET_NEXT_PAGE_FLAG_REPOS = "SET_NEXT_PAGE_FLAG_REPOS";
export const SET_REPOSITORY_LINK = "SET_REPOSITORY_LINK";
