export const FETCH_COMMITS_REQUEST = "FETCH_COMMITS_REQUEST";
export const FETCH_COMMITS_SUCCESS = "FETCH_COMMITS_SUCCESS";
export const FETCH_COMMITS_FAILURE = "FETCH_COMMITS_FAILURE";
export const FETCH_NEXT_PAGE = "FETCH_NEXT_PAGE";

export const SET_NEXT_PAGE_FLAG_COMMITS = "SET_NEXT_PAGE_FLAG_COMMITS";
export const SET_COMMITS_LINK = "SET_COMMITS_LINK";
